version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(levelname)-8s - %(name)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: /var/log/security_system/application.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8

loggers:
    security_system:
        level: WARN
        handlers: [console]
        propagate: no

root:
    level: INFO
    handlers: [console, file_handler]

